name: CI

on:
  - push
  - workflow_dispatch

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: gabrielrufino/node-ci@v1
        with:
          node-version: ${{ matrix.node-version }}
